### ISSUE TITLE
Inter Semibold wrong 400 weight

### ISSUE THREAD

**Issue by pws-pm** [tokens-bruecke/figma-plugin#23]
Hi Everybody,
I got an issue with the Inter Semibold font that should be exported in weight 600 but in the JSON is weight 400, just like the regular weight.

Thanks,
Luigi.

<img width="1840" alt="correct" src="https://github.com/tokens-bruecke/figma-plugin/assets/147876953/5e5df404-1596-46e8-9fd3-29a226103941">
<img width="1840" alt="wrong" src="https://github.com/tokens-bruecke/figma-plugin/assets/147876953/015a953d-90ad-4278-a4e3-8465d3d82bc7">

**Comment by JeroenRoodIHS** [comment]
The issue will be solved by this PR: https://github.com/tokens-bruecke/figma-plugin/pull/20

The problem was caused by case-sensitivity regarding the font weight names.

**Comment by PavelLaptev** [comment]
@JeroenRoodIHS thanks for the PR.
@pws-pm I've just published a new version

**Comment by pws-pm** [comment]
![Screenshot 2024-04-15 at 10 33 35](https://github.com/tokens-bruecke/figma-plugin/assets/147876953/fc02d2ab-1ef6-4a91-ba14-5f7103aeac70)
@PavelLaptev 
Thanks for the new version, however, I tried to re-run the plugin and I still see the issue. Am I doing something wrong? thanks!

**Comment by PavelLaptev** [comment]
Thanks for the report @pws-pm
I'll check it out

**Comment by PavelLaptev** [comment]
@pws-pm fixed :-) 
the problem was that Figma return the font-weight for inter like this `semi bold` so I added a regex to concat words.

**Comment by pws-pm** [comment]
Amazing, thanks!
